### ISSUE TITLE
How to support Scala/Java syntax highlight

### ISSUE THREAD

**Issue by pandaforme** [kelyvin/caffeine-theme#7] opened 2016-05-19 13:07 UTC
I would like to add Scala/Java syntax highlight, but I don't know how to do it.

I tried to modify `assets/vendor/prism/gulpfile.js` and execute `gulp build`, but it doesn't work...

Please give me some hints, thanks

**Comment by andrewlock** [comment] 2016-05-19 15:17
You need to add the correct prism language `.js` file to `gulpfile.js` so looks like you were nearly there.

Update the `src.js.vendor` object and add the paths to your language files just after `prism.js`. It should look something like this: 

```javascript
src = {
    js: {
        fonts: [],
        main: [],
        vendor: [
            "assets/js/src/libs/subbscribe.js",
            "assets/vendor/ghostHunter/jquery.ghostHunter.min.js",
            "assets/vendor/fitvids/jquery.fitvids.js",
            "assets/vendor/reading-time/build/readingTime.min.js",
            "assets/vendor/prism/prism.js",
            "assets/vendor/prism/components/prism-java.min.js",
            "assets/vendor/prism/components/prism-scala.min.js",
            "assets/vendor/toastr/toastr.min.js",
            "assets/vendor/store-js/store.min.js"
        ]
    },
};
```

Then in your ghost editor you need to indicate which language to use for a block using the following syntax: 

<pre><code>
This is example code for java:

```language-java
public void method()
{

}
```

</code></pre>

**Comment by kelyvin** [comment] 2016-05-20 04:57
Thanks for answering @andrewlock! Yep he is correct, this should be the appropriate way to do it.

**Comment by pandaforme** [comment] 2016-05-20 16:27
I've tried to modify `caffeine-theme\gulpfile.js` and add two language files: `assets/vendor/prism/components/prism-java.min.js` and `assets/vendor/prism/components/prism-scala.min.js', and execute `gulp build`.

@andrewlock

**Comment by andrewlock** [comment] 2016-05-20 17:22
Do you get any errors when you run `gulp build`?

**Comment by kelyvin** [comment] 2016-05-20 19:59
Building a docker image for this is a little overkill so I don't want to get into that just yet and want to focus more on helping you figure out the problem in case others encounter the same issue

When you say you "can't see the home page", does the app load but you get a blank white screen? If so, can you open up your developer tools to see if there is an error on the console? If you don't see the page load at all, make sure that Ghost is also already running as described [here](https://github.com/kelyvin/caffeine-theme#first-steps).

I tried to import those two JS prism libraries myself and it worked. It possibly could be the npm and node versions, my npm version is v3.8.1 and my node version is v4.4.0, but I feel that shouldn't be the issue. Can you try upgrade npm to see if that may be the issue? 

Thanks!

**Comment by andrewlock** [comment] 2016-05-20 20:25
Just for reference, my npm version is 2.7.4 and node version is 0.12.2.

**Comment by pandaforme** [comment] 2016-05-21 17:19
I've upgraded npm to 3.9.3 and followed the instructions: https://github.com/kelyvin/caffeine-theme#first-steps.

I cloned a new caffeine-theme repo and don't modify any thing. 
Then executing `gulp`, I can't see any article and button.

<img width="1280" alt="screen shot 2016-05-22 at 00 55 40" src="https://cloud.githubusercontent.com/assets/3078300/15449731/ed47b320-1fb8-11e6-8146-ab052c24a7bf.png">
error message:
<img width="1280" alt="screen shot 2016-05-22 at 00 55 54" src="https://cloud.githubusercontent.com/assets/3078300/15449737/1017ef78-1fb9-11e6-92fa-90103280122e.png">

If I cloned a new caffeine-theme repo and started `Ghost`. Don't execute `gulp` and access `http://localhost:2368`. The web page is complete.

I guess that `gulp` generates wrong js files...

Thanks~

**Comment by andrewlock** [comment] 2016-05-21 17:34
Very strange, `lunr.js` is included as part of the `ghostHunter.js` library which is built in the vendor section that you are modifying. Could you post your `gulpfile.js` so we can take a look? 

Cheers

**Comment by kelyvin** [comment] 2016-05-22 22:54
Thanks a bunch @pandaforme for your patience and for reporting this issue. I have figured out the issue given the latest screenshots and @andrewlock validating the issue is from ghostHunter.js.

Since ghostHunter doesn't have any bower support or release tags, we are pulling the latest from master every time. Looks like ghostHunter had a major update in the past couple of months that switches some of their implementation to use the new Ghost API, which is current unstable and in beta. As a result, one of their latest commits probably caused this issue that you are experiencing. 

So to resolve this issue, I will perform a "version lock" on all of our bower packages to the latest stable versions. Unfortunately, bower does not currently support a "shrinkwrap" equivalent to npm, so this will have to do for now. I will do the same for our node modules, but I would like to do an audit of those dependencies before proceeding, so I will leave our package.json as is for now. 

I have checked in the latest changes to bower.json, please pull the latest and let me know if you still run into any issues.

Thanks!

**Comment by pandaforme** [comment] 2016-05-24 05:55
@kelyvin @andrewlock Thanks for your help, it works!
I can add prism java/scala language js file.

You can close the issue~

**Comment by kelyvin** [comment] 2016-05-24 06:53
woo hoo! Will do!

**Closed by kelyvin** 2016-05-24 06:53 UTC

**Comment by andrewlock** [comment] 2016-05-26 08:26
Nice detective work @kelyvin 😄

**Comment by antranthien** [comment] 2016-08-13 17:54
Hi, I tried adding "assets/vendor/prism/components/prism-java.min.js" to the gulpfile.js but the syntax for Java code doesn't get highlighted. Did I miss anything?

**Comment by kelyvin** [comment] 2016-08-14 10:14
Hi @antranthien, when you using prism.js, after you import the proper asset to the gulpfile, you have to make sure that when you're adding code blcoks to the markdown of your posts, that you properly define the language type of the code block. Similar to the highlighted portion of the image below.

![example_editor](https://cloud.githubusercontent.com/assets/1530102/17648520/ff7f29e6-61cc-11e6-8bd6-beef6495a5b4.png)

In the example above, I'm defining this code block as `javascript`, can you verify whether you are also defining your code block as `java`? 

If this doesn't resolve your issue, then I can do a deeper dive and see what's happening. 

Thanks!

**Comment by antranthien** [comment] 2016-08-16 15:06
@kelyvin : Thanks. Got it working now :)
