### ISSUE TITLE
Back Arrow on Static Pages

### ISSUE THREAD

**Issue by BMonsalvatge** [kelyvin/caffeine-theme#57] opened 2018-01-22 18:32 UTC
Found an interesting error when creating static pages.  Other than the "About" page, if you make a story with the title About and make it static, it appears that all other static pages have a back arrow that redirects to the URL domain.com/pagename/#open.

Anyone have any ideas on how to correct the URL or remove the arrow all together.  I'll be searching around and see if I can fix it myself.

**Comment by kelyvin** [comment] 2018-01-24 22:57
Can you possibly show me an example of what you're talking about? That way I can try reemulating it and see what the root cause of the problem is. That will help me determine if it's an issue with the blogging platform or with my theme. Thanks!

**Comment by BMonsalvatge** [comment] 2018-02-23 18:04
Sorry it took me so long to get back.  You can see the issue here: https://bryanmonsalvatge.com/projects/

**Comment by kelyvin** [comment] 2018-02-24 23:04
Okay now I understand! Let me take a look and see I can find a solution for this. Stay tuned.

**Comment by kelyvin** [comment] 2018-02-26 02:51
Hi @BMonsalvatge, I have released a patch fix for the back button issue you were running into. Now if you click on the back button, it will redirect to your home page. Let me know if this works for you!

You can download the latest release here: https://github.com/kelyvin/caffeine-theme/releases/tag/v3.0.6

**Comment by kelyvin** [comment] 2018-03-14 00:29
@BMonsalvatge - since this has not been updated, I am going to close this issue. But feel free to reopen if you still have any issues!

**Closed by kelyvin** 2018-03-14 00:29 UTC
